# Generated by Django 4.2.9 on 2025-05-17 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "Codigo",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Al", models.CharField(max_length=50)),
                (
                    "Ano",
                    models.IntegerField(
                        choices=[
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                            (2025, 2025),
                        ]
                    ),
                ),
                (
                    "LocalArmazenamento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("IsaSipa", models.CharField(blank=True, max_length=50, null=True)),
                ("DataSipa", models.DateField(blank=True, null=True)),
                (
                    "TipoVenda",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Desinvestimento", "Desinvestimento"),
                            ("Sucateamento", "Sucateamento"),
                            ("Vendido", "Vendido"),
                            ("Leilão", "Leilão"),
                            ("", ""),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "TipoMaterial",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Inservivel", "Inservivel"),
                            ("Residuo Valorizavel", "Residuo Valorizavel"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("IsaEnvioArm", models.CharField(blank=True, max_length=50, null=True)),
                ("DataEnvoArm", models.DateField(blank=True, null=True)),
                ("DataRecebimentoLote", models.DateField(blank=True, null=True)),
                ("PrazoEntrega", models.DateField(blank=True, null=True)),
                ("DataEntrega", models.DateField(blank=True, null=True)),
                ("PrazoConciliação", models.DateField(blank=True, null=True)),
                ("DataConciliação", models.DateField(blank=True, null=True)),
                ("DataUltimaBaixa", models.DateField(blank=True, null=True)),
                ("PrazodeBaixa", models.DateField(blank=True, null=True)),
                ("DataPagamento", models.DateField(blank=True, null=True)),
                ("PrazoPagamento", models.DateField(blank=True, null=True)),
                ("DataCancelamento", models.DateField(blank=True, null=True)),
                ("Cancelado", models.BooleanField(default=False)),
                (
                    "Prioridade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Urgente", "Urgente"),
                            ("Alta", "Alta"),
                            ("Média", "Média"),
                            ("Baixa", "Baixa"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "Status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Pendente data de Recebimento",
                                "Pendente data de Recebimento",
                            ),
                            ("Pendente de Pagamento", "Pendente de Pagamento"),
                            ("Pendente de Entrega", "Pendente de Entrega"),
                            ("Pendente de Medição", "Pendente de Medição"),
                            ("Pendente de Conciliação", "Pendente de Conciliação"),
                            (
                                "Cancelado Pendente de Conciliação",
                                "Cancelado Pendente de Conciliação",
                            ),
                            ("Conciliado", "Conciliado"),
                            ("Cancelado Conciliado", "Cancelado Conciliado"),
                            ("Em Negociação-Superbid", "Em Negociação-Superbid"),
                            (
                                "Sucateado Pendente de Baixa",
                                "Sucateado Pendente de Baixa",
                            ),
                            ("Sucateado Baixado", "Sucateado Baixado"),
                            ("Em Leilão", "Em Leilão"),
                            ("Entrega Programada", "Entrega Programada"),
                            (
                                "Nota Pendente de Assinatura",
                                "Nota Pendente de Asssinatura",
                            ),
                            ("", ""),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("DataMedicao", models.DateField(blank=True, null=True)),
                ("PrazoMedicao", models.DateField(blank=True, null=True)),
                ("PrazoConciliacaoCancelado", models.DateField(blank=True, null=True)),
                ("DataConciliacaoCancelado", models.DateField(blank=True, null=True)),
                ("DataAuditoria", models.DateField(blank=True, null=True)),
                ("DataNegociacao", models.DateField(blank=True, null=True)),
                ("EmNegociacao", models.BooleanField(default=False)),
                ("DataPagamentoLoteEx", models.DateField(blank=True, null=True)),
                (
                    "WriteDownStatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("WRITE DOWN COMPLETO", "WRITE DOWN COMPLETO"),
                            ("WRITE DOWN PARCIAL", "WRITE DOWN PARCIAL"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "DtatusDeEntrega",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SEM ENTREGA", "SEM ENTREGA"),
                            ("ENTREGA PARCIAL", "ENTREGA PARCIAL"),
                            ("ENTREGA FINALIZADA", "ENTREGA FINALIZADA"),
                        ],
                        default="SEM ENTREGA",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("PrazoEntregaAdicional", models.IntegerField(default=0)),
                ("PrazoPagamentoAdicional", models.IntegerField(default=0)),
                ("DataCadastroUltimaNota", models.DateField(blank=True, null=True)),
                ("DataSolicitacaoConciliacao", models.DateField(blank=True, null=True)),
                (
                    "DataSolicitacaoConciliacaoCancelado",
                    models.DateField(blank=True, null=True),
                ),
                ("Perdeuprazoentrega", models.BooleanField(default=False)),
                (
                    "MotivoPercaPrazo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Notificacao", models.BooleanField(default=False)),
                (
                    "Responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
