# Generated by Django 4.2.9 on 2025-05-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='DataEnvoArm',
            new_name='DataEnvioArm',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='DtatusDeEntrega',
            new_name='StatusDeEntrega',
        ),
    ]
